import * as fs from "fs";
import * as path from "path";
import { LLMClient } from "../../llm-client";
import { ManifestEntry, GenLock } from "../types";
import { buildStandardGeneratorPrompt } from "../prompts";
import { StackConfig } from "../stacks.config";
import { collectSignatures } from "../utils/signature-utils";
import {
  getTargetPathForEntry,
  shouldSkipGeneration,
} from "../compile-plan";

type PendingWrite = {
  targetPath: string;
  content: string;
  signature: string | null;
  lockKey: string;
  lockHash: string;
};

export class StandardRunner {
  constructor(
    private llmClient: LLMClient,
    private manifestPath: string,
    private outputBaseDir: string,
    private lockFilePath: string,
    private stackConfig: StackConfig,
  ) {}

  public async run(options: { force?: boolean; debug?: boolean } = {}) {
    const startTime = Date.now();
    const { force = false, debug = false } = options;

    if (!fs.existsSync(this.manifestPath)) {
      console.error(`❌ Manifest not found: ${this.manifestPath}`);
      return;
    }

    if (force) {
      console.log("⚡ Force mode enabled: All files will be regenerated.");
    }

    const manifest: ManifestEntry[] = JSON.parse(
      fs.readFileSync(this.manifestPath, "utf-8"),
    );
    let lock: GenLock = {};

    if (fs.existsSync(this.lockFilePath)) {
      lock = JSON.parse(fs.readFileSync(this.lockFilePath, "utf-8"));
    }

    console.log(`🚀 Starting Generation Pipeline`);
    console.log(`📂 Manifest: ${this.manifestPath}`);
    console.log(`🎯 Output Base: ${this.outputBaseDir}`);

    let generatedCount = 0;
    let skippedCount = 0;
    const pendingWrites: PendingWrite[] = [];

    const totalFiles = manifest.length;
    let processedIndex = 0;

    for (const entry of manifest) {
      processedIndex++;
      const remaining = totalFiles - processedIndex;
      const progressInfo = `[${processedIndex}/${totalFiles}]`;

      // 1. Skip se non c'è un path di implementazione (es. file puramente astratti)
      if (!entry.implementationPath) {
        console.log(
          `${progressInfo} ⏩ Skipping ${path.basename(entry.sourceFile)} (Missing '**Implementation**: <path>' in ISL)`,
        );
        skippedCount++;
        continue;
      }

      const buildContext = fs.readFileSync(entry.buildFile, "utf-8");
      const pathInfo = getTargetPathForEntry(
        entry,
        buildContext,
        this.outputBaseDir,
        this.stackConfig,
      );
      if (!pathInfo) {
        skippedCount++;
        continue;
      }
      const { targetPath, relativeImplPath } = pathInfo;

      if (shouldSkipGeneration(entry, lock, targetPath, force)) {
        console.log(
          `${progressInfo} ⏭️  Skipping ${path.basename(entry.sourceFile)} (Unchanged)`,
        );
        skippedCount++;
        continue;
      }

      const targetExists = fs.existsSync(targetPath);

      if (force) {
        console.log(
          `${progressInfo} ⚡ Force Rebuild: ${path.basename(entry.sourceFile)}`,
        );
      } else if (!targetExists) {
        console.log(
          `${progressInfo} 🆕 Creating: ${path.basename(entry.sourceFile)}`,
        );
      } else {
        console.log(
          `${progressInfo} 📝 Updating: ${path.basename(entry.sourceFile)} (Changed)`,
        );
      }

      console.log(
        `${progressInfo} 🤖 Generating ${path.basename(entry.sourceFile)} -> ${relativeImplPath} (${remaining} remaining)`,
      );

      // NEW: Dependency Injection (Dynamic Linking)
      const signatures = collectSignatures(
        buildContext,
        this.outputBaseDir,
        this.stackConfig,
      );

      const prompt = buildStandardGeneratorPrompt(
        buildContext,
        signatures,
        this.stackConfig,
      );

      if (debug) {
        const debugDir = path.join(this.outputBaseDir, "promptDebug");
        if (!fs.existsSync(debugDir)) {
          fs.mkdirSync(debugDir, { recursive: true });
        }
        const debugFilePath = path.join(
          debugDir,
          path.basename(entry.sourceFile),
        );
        fs.writeFileSync(debugFilePath, prompt);
        console.log(
          `   🐛 Debug prompt saved: ${path.join("promptDebug", path.basename(entry.sourceFile))}`,
        );
      }

      // 4. Chiama l'LLM tramite il client dedicato
      const rawOutput = await this.llmClient.generateRaw(prompt);
      const { code, signature } = this.parseMultipartOutput(rawOutput);

      const header = `/**\n * DO NOT EDIT THIS FILE DIRECTLY\n * ----------------------------------\n * This file was generated by ISL Compiler.\n * Source: ${path.basename(entry.sourceFile)}\n * Edit the ISL file instead.\n */\n\n`;
      pendingWrites.push({
        targetPath,
        content: header + code,
        signature: signature ?? null,
        lockKey: entry.buildFile,
        lockHash: entry.hash,
      });
      generatedCount++;
    }

    // Publish phase (transaction-like):
    // files are written only after the entire generation loop succeeds.
    for (const item of pendingWrites) {
      const targetDir = path.dirname(item.targetPath);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }
      fs.writeFileSync(item.targetPath, item.content);

      if (item.signature) {
        const sigPath = item.targetPath + ".sign.ts";
        fs.writeFileSync(sigPath, item.signature);
        console.log(`   📝 Signature saved: ${path.basename(sigPath)}`);
      }

      lock[item.lockKey] = item.lockHash;
    }

    // Salva lo stato aggiornato solo dopo publish completo
    fs.writeFileSync(this.lockFilePath, JSON.stringify(lock, null, 2));
    const endTime = Date.now();
    const duration = ((endTime - startTime) / 1000).toFixed(2);
    console.log(
      `✅ Generation Completed in ${duration}s. (Generated: ${generatedCount}, Skipped: ${skippedCount})`,
    );

    if (generatedCount === 0 && skippedCount > 0) {
      console.log(
        `💡 Hint: Ensure your ISL files have a '**Implementation**: ./file.[extension of language]' header.`,
      );
    }
  }

  private parseMultipartOutput(output: string): {
    code: string;
    signature: any;
  } {
    const codeMatch = output.match(/#\[CODE\]([\s\S]*?)#\[CODE-END\]/);
    const sigMatch = output.match(/#\[SIGNATURE\]([\s\S]*?)#\[SIGNATURE-END\]/);

    let code = codeMatch && codeMatch[1] ? codeMatch[1].trim() : output.trim();
    let signature = null;

    // Clean markdown code blocks if present
    const mdMatch = code.match(/^```(?:\w+)?\n([\s\S]*?)```$/);
    if (mdMatch) code = mdMatch[1].trim();

    if (sigMatch && sigMatch[1]) {
      try {
        let sigStr = sigMatch[1].trim();
        const mdSigMatch = sigStr.match(/^```(?:\w+)?\n([\s\S]*?)```$/);
        if (mdSigMatch) sigStr = mdSigMatch[1].trim();
        signature = sigStr;
      } catch (e) {
        console.warn("   ⚠️ Error parsing #[SIGNATURE] block");
      }
    }

    return { code, signature };
  }
}
